from datetime import date, datetime, timedelta, timezone
from io import BytesIO
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.models.entry import Entry
from app.models.interaction_flag import InteractionFlag
from app.models.medication import Medication
from app.models.user import User


def _plain_text(value: object) -> str:
    """Escape user-authored text before placing it into a ReportLab Paragraph."""
    return escape(str(value)).replace("\n", "<br/>")


def _format_date(value: date | datetime | None) -> str:
    if value is None:
        return "—"
    if isinstance(value, datetime):
        return value.astimezone(timezone.utc).strftime("%b %-d, %Y")
    return value.strftime("%b %-d, %Y")


def _footer(generated_at: datetime):
    timestamp = generated_at.astimezone(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    def draw(canvas, document):
        canvas.saveState()
        width, _ = letter
        canvas.setStrokeColor(colors.HexColor("#d5dde3"))
        canvas.setLineWidth(0.5)
        canvas.line(document.leftMargin, 0.55 * inch, width - document.rightMargin, 0.55 * inch)
        canvas.setFillColor(colors.HexColor("#667781"))
        canvas.setFont("Helvetica", 8)
        canvas.drawString(document.leftMargin, 0.35 * inch, f"Generated by Aegis · {timestamp}")
        canvas.drawRightString(width - document.rightMargin, 0.35 * inch, f"Page {document.page}")
        canvas.restoreState()

    return draw


def generate_patient_pdf(
    patient: User,
    entries: list[Entry],
    medications: list[Medication],
    flags: list[InteractionFlag],
) -> bytes:
    """Generate an emergency-oriented summary of a patient's care record."""
    generated_at = datetime.now(timezone.utc)
    buffer = BytesIO()
    document = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.55 * inch,
        leftMargin=0.55 * inch,
        topMargin=0.55 * inch,
        bottomMargin=0.8 * inch,
        title=f"Aegis Medical Summary - {patient.name}",
        author="Aegis",
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "AegisTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=21,
        leading=25,
        textColor=colors.HexColor("#12343b"),
        spaceAfter=5,
    )
    patient_style = ParagraphStyle(
        "PatientName",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=17,
        textColor=colors.HexColor("#244c55"),
        spaceAfter=3,
    )
    note_style = ParagraphStyle(
        "EmergencyNote",
        parent=styles["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=8.5,
        leading=12,
        textColor=colors.HexColor("#586b73"),
        spaceAfter=11,
    )
    section_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=16,
        textColor=colors.HexColor("#12343b"),
        spaceBefore=13,
        spaceAfter=7,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#31454d"),
    )
    small_style = ParagraphStyle(
        "Small",
        parent=body_style,
        fontSize=8,
        leading=11,
    )
    flag_style = ParagraphStyle(
        "Flag",
        parent=body_style,
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#6f1d1b"),
    )
    empty_style = ParagraphStyle(
        "Empty",
        parent=body_style,
        fontName="Helvetica-Oblique",
        textColor=colors.HexColor("#667781"),
    )

    story = [
        Paragraph("Aegis Medical Summary", title_style),
        Paragraph(_plain_text(patient.name), patient_style),
        Paragraph(f"Exported {_format_date(generated_at)}", small_style),
        Spacer(1, 5),
        Paragraph(
            "Generated for emergency/care reference — not a substitute for full medical records",
            note_style,
        ),
        HRFlowable(width="100%", thickness=0.8, color=colors.HexColor("#9ab7ba")),
    ]

    entry_by_id = {entry.id: entry for entry in entries}
    active_medications = sorted(
        (medication for medication in medications if medication.is_active),
        key=lambda medication: medication.start_date,
        reverse=True,
    )

    story.append(Paragraph("Active Medications", section_style))
    if active_medications:
        medication_rows = [
            [
                Paragraph("Drug name", small_style),
                Paragraph("Dosage", small_style),
                Paragraph("Frequency", small_style),
                Paragraph("Prescribing specialty", small_style),
                Paragraph("Start date", small_style),
            ]
        ]
        for medication in active_medications:
            prescribing_entry = entry_by_id.get(medication.entry_id)
            specialty = prescribing_entry.specialty_tag if prescribing_entry else "Unknown"
            medication_rows.append(
                [
                    Paragraph(_plain_text(medication.drug_name), body_style),
                    Paragraph(_plain_text(medication.dosage), body_style),
                    Paragraph(_plain_text(medication.frequency), body_style),
                    Paragraph(_plain_text(specialty), body_style),
                    Paragraph(_format_date(medication.start_date), body_style),
                ]
            )
        medication_table = Table(
            medication_rows,
            colWidths=[1.35 * inch, 0.85 * inch, 1.1 * inch, 1.55 * inch, 1.05 * inch],
            repeatRows=1,
            hAlign="LEFT",
        )
        medication_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#dcebed")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#163f47")),
                    ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#c6d4d7")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        story.append(medication_table)
    else:
        story.append(Paragraph("No active medications recorded.", empty_style))

    if flags:
        medication_by_id = {medication.id: medication for medication in medications}
        flag_rows = []
        for flag in flags:
            medication_a = medication_by_id.get(flag.medication_id_a)
            medication_b = medication_by_id.get(flag.medication_id_b)
            involved = " + ".join(
                medication.drug_name
                for medication in (medication_a, medication_b)
                if medication
            ) or "Medication details unavailable"
            flag_rows.append(
                [
                    Paragraph(
                        f"<b>{_plain_text(flag.severity.value.title())} severity</b><br/>"
                        f"<b>Involved medications:</b> {_plain_text(involved)}<br/>"
                        f"{_plain_text(flag.description)}",
                        flag_style,
                    )
                ]
            )

        story.append(Paragraph("Unresolved Safety Flags", section_style))
        flag_table = Table(flag_rows, colWidths=[6.0 * inch], hAlign="LEFT")
        flag_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#fff1ef")),
                    ("BOX", (0, 0), (-1, -1), 1.1, colors.HexColor("#c94f4a")),
                    ("LINEBELOW", (0, 0), (-1, -2), 0.5, colors.HexColor("#edbbb7")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 9),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 9),
                    ("TOPPADDING", (0, 0), (-1, -1), 8),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ]
            )
        )
        story.append(flag_table)

    cutoff = datetime.now(timezone.utc) - timedelta(days=90)
    recent_entries = sorted(
        (
            entry
            for entry in entries
            if entry.entry_type.value in {"note", "diagnosis"}
            and entry.created_at >= cutoff
        ),
        key=lambda entry: entry.created_at,
    )[:20]

    story.append(Paragraph("Recent Entries", section_style))
    if recent_entries:
        for entry in recent_entries:
            story.extend(
                [
                    Paragraph(
                        f"<b>{_plain_text(entry.title)}</b> · {_plain_text(entry.entry_type.value.replace('_', ' ').title())}",
                        body_style,
                    ),
                    Paragraph(
                        f"{_format_date(entry.created_at)} · {_plain_text(entry.specialty_tag)}",
                        small_style,
                    ),
                    Paragraph(_plain_text(entry.content), body_style),
                    Spacer(1, 8),
                ]
            )
    else:
        story.append(Paragraph("No notes or diagnoses recorded in the last 90 days.", empty_style))

    document.build(story, onFirstPage=_footer(generated_at), onLaterPages=_footer(generated_at))
    return buffer.getvalue()
