"""add resolution_note to interaction_flags

Revision ID: 15fd4c8f96f4
Revises: e25346d1b283
Create Date: 2026-07-31 00:18:38.023274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15fd4c8f96f4'
down_revision: Union[str, Sequence[str], None] = 'e25346d1b283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interaction_flags', sa.Column('resolution_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interaction_flags', 'resolution_note')
    # ### end Alembic commands ###
