"""create care_circles table

Revision ID: e99ae4676bd6
Revises: 5556516ee5a1
Create Date: 2026-07-30 18:44:57.572817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e99ae4676bd6'
down_revision: Union[str, Sequence[str], None] = '5556516ee5a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_circles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('permission_scope', sa.Enum('FULL', 'NOTES_ONLY', 'PRESCRIPTIONS_ONLY', name='permissionscope'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REVOKED', name='carecirclestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'doctor_id', name='uq_patient_doctor')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('care_circles')
    # ### end Alembic commands ###
